### ISSUE TITLE
Speedtrap "crash"

### ISSUE THREAD

**Issue by Ericsson2003** [ExOptsTeam/NFSMWRaceFixes#3]
Game quits unexpectedly, when you pass first fotoradar on Speedtrap events.

**Comment by trackmaniamatt** [comment]
I have also tested this, and I too, am having the same problem. Not sure what's causing this.

**Comment by nlgzrgn** [comment]
The issue is fixed with v1.0.0.1338 release. Thanks for reporting, have fun!
